name: CI

on:
  workflow_call:

env:
  ARTIFACT: unset
  DIRECTORY: unset
  SCCACHE_GHA_ENABLED: "true"

jobs:
  download:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7

      - name: Download
        run: ./tools/download.sh

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: source
          path: ${{ env.ARTIFACT }}
          archive: false

      - name: Upload Timestamp
        uses: actions/upload-artifact@v7
        with:
          name: timestamp
          path: TIMESTAMP
          archive: false

      - name: Upload Version
        uses: actions/upload-artifact@v7
        with:
          name: version
          path: VERSION
          archive: false

      - name: Generate Build Matrix
        id: matrix
        run: |
          echo "matrix=$(./tools/matrix.sh)" >> "$GITHUB_OUTPUT"
          tools/matrix.sh

  build:
    needs: [download]
    name: "${{ matrix.platform }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.download.outputs.matrix) }}

    container: ${{ matrix.container }}

    defaults:
      run:
        shell: >-
          ${{ case(
            matrix.platform == 'windows', 'pwsh',
            matrix.platform == 'mingw', 'msys2 {0}',
            'bash'
          ) }}

    env:
      BASH_SHELL: ${{ matrix.platform == 'mingw' && 'msys2 {0}' || 'bash' }}
      # change this if you need jom, ninja, cmake etc
      MAKE: ninja

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # Setup
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Setup MSYS2
        if: matrix.platform == 'mingw'
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.arch == 'amd64' && 'ucrt64' || 'clangarm64' }}
          update: true
          install: >-
            git tar curl
          pacboy: >-
            toolchain:p cmake:p ninja:p

      - name: Setup MSVC
        if: matrix.platform == 'windows'
        uses: crueter/setup-msvc-dev@master

      - name: Setup Environment
        shell: bash
        run: |
          . tools/vars.sh
          {
            echo "DIRECTORY=$DIRECTORY"
            echo "ARTIFACT=$ARTIFACT"
            echo "OUT_DIR=$GITHUB_WORKSPACE/out"

            echo "ARCH=${{ matrix.arch }}"
            echo "PLATFORM=${{ matrix.platform }}"
          } >> "$GITHUB_ENV"

          mkdir -p out

      - name: Install Dependencies (Linux/macOS)
        if: matrix.platform == 'linux' || matrix.platform == 'macos'
        run: ./deps/${{ matrix.platform }}.sh

      # Download + extract
      - name: Download
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT }}

      - name: Download Timestamp
        uses: actions/download-artifact@v8
        with:
          name: TIMESTAMP

      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true
          Set-MpPreference -DisableBehaviorMonitoring $true
          Set-MpPreference -DisableArchiveScanning $true

      - name: Extract
        run: tar xf ${{ env.ARTIFACT}}

      # configure
      - name: Configure
        run: bash ./tools/configure.sh

      - name: Build
        run: ${{ env.MAKE }} -j8
        working-directory: ${{ env.DIRECTORY }}

      - name: Package
        run: bash ./tools/package.sh

      - name: Upload Tarball
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}
          path: artifacts/*.tar.zst
          archive: false

      - name: Upload Sum
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-sha512sum
          path: artifacts/*.tar.zst.sha512sum
          archive: false