name: Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION: unset

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Get Version
        run: echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: SDL3 ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          files: |
            *.tar.zst*

          make_latest: true