name: Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Get Version
        run: cat VERSION

      - name: Check artifacts
        run: find -name "*.tar.zst*"